// Bundled "Sqooky's Default" performance preset, derived from the
// OptimizationLock project: https://github.com/Sqooky/OptimizationLock
// (GPL-3.0, by Sqooky and contributors). Grimoire applies these values onto
// the user's existing gameinfo.gi instead of replacing the whole file, so
// Grimoire's SearchPaths block (mods, overflow folders, deadworks content)
// and any game-update changes survive.
//
// Generated from upstream ver. 2.4.6 by diffing "Sqooky's .gi/gameinfo.gi"
// against the repo's "clean gameinfo.gi" baseline at the section/key level.
// Deliberately excluded:
// - FileSystem/SearchPaths: Grimoire owns that block (see system.ts).
// - r_aspectratio "2.50": active upstream but its own comment says it should
//   be commented out (changes FOV); reported upstream.
// - Editor-only sections (Hammer, pulse, ResourceCompiler, ContentBuilder)
//   and AllowKeyChordBindings (marked personal by the author).
//
// To update for a new upstream release: re-run the diff against the new
// clean baseline and regenerate these tables. Do not hand-tune values here;
// upstream is the source of truth for what the preset contains.

/** One key edit inside a gameinfo.gi section. `remove: true` comments the
 *  existing line out (engine falls back to its built-in default), matching
 *  upstream configs that delete stock keys outright. */
export interface SectionOp {
    /** Nested section path from the root GameInfo block, e.g. ['Engine2', 'RenderingPipeline']. */
    path: string[];
    key: string;
    value?: string;
    remove?: boolean;
}

export const PRESET_ID = 'sqooky-default';
export const PRESET_NAME = "Sqooky's Default (OptimizationLock)";
export const PRESET_VERSION = '2.4.6';
export const PRESET_SOURCE_URL = 'https://github.com/Sqooky/OptimizationLock';

/** ConVars exposed as reversible user controls in Settings. Values are only
 * written when the user changes a control; they are not forced by the FPS
 * preset itself. */
export const HUD_CONVARS = [
    { key: 'citadel_unit_status_use_new', on: 'true', off: 'false' },
    { key: 'citadel_unit_status_use_v2', on: 'true', off: 'false' },
    { key: 'citadel_unit_status_single_bar_mode', on: 'true', off: 'false' },
    { key: 'citadel_unit_status_use_v2_for_nonplayers', on: 'true', off: 'false' },
    { key: 'citadel_unit_status_allies_see_thru_walls', on: 'true', off: 'false' },
    { key: 'citadel_hud_objective_health_enabled', on: '2', off: '0' },
    { key: 'citadel_damage_offscreen_indicator_disabled', on: 'false', off: 'true' },
    { key: 'citadel_damage_text_show_effectiveness', on: '1', off: '0' },
] as const;

// Review against the live game's ConVars after Deadlock updates. Keep these
// advanced controls bounded: they are client-side presentation/readability
// settings, not gameplay settings.
export const ADVANCED_GAMEINFO_CONVARS = [
    { key: 'citadel_unit_status_allies_see_thru_walls_max_distance', min: 0, max: 200, step: 5 },
    { key: 'citadel_minimap_unit_click_radius', min: 400, max: 1200, step: 25 },
    { key: 'citadel_minimap_player_width', min: 4, max: 12, step: 0.5 },
    { key: 'citadel_minimap_local_player_width', min: 6, max: 16, step: 0.5 },
    { key: 'citadel_minimap_max_icon_shrink', min: 0.4, max: 1, step: 0.05 },
    { key: 'citadel_minimap_overlap_scan_distance', min: 0, max: 40, step: 1 },
    { key: 'citadel_minimap_zip_line_thickness', min: 1, max: 8, step: 0.5 },
    { key: 'minimap_update_rate_hz', min: 5, max: 60, step: 5 },
] as const;

/** Engine-section edits outside ConVars. The SceneSystem shadow/fog keys are
 *  a large share of the preset's fps win. */
export const SECTION_OPS: SectionOp[] = [
    { path: ['NetworkSystem'], key: 'UseSerializedEntityPool', value: '1' },
    { path: ['NetworkSystem', 'BetaUniverse'], key: 'FakeLag', value: '0' },
    { path: ['NetworkSystem', 'BetaUniverse'], key: 'FakeLoss', value: '0' },
    { path: ['Engine2'], key: 'SinglePlayerAsyncRendering', value: '1' },
    { path: ['Engine2', 'RenderingPipeline'], key: 'AmbientOcclusionProxies', value: '0' },
    { path: ['RenderSystem'], key: 'AllowPartialMipChainImmediateTexLoads', value: '1' },
    { path: ['RenderSystem'], key: 'UseHardwareGammaRamp', value: '0' },
    { path: ['RenderSystem'], key: 'IndexBufferPoolSizeMB', value: '64' },
    { path: ['RenderSystem'], key: 'MinStreamingPoolSizeMB', value: '512' },
    { path: ['Particles'], key: 'EnableMixedResolution', value: '1' },
    { path: ['Particles'], key: 'GpuImplicitRendererManifest', value: '1' },
    { path: ['Particles'], key: 'ParticlesFoggedByDefault', value: '0' },
    { path: ['Particles'], key: 'PerVertexLighting', value: '0' },
    { path: ['SceneSystem'], key: 'DisableShadowFullSort', value: '1' },
    { path: ['SceneSystem'], key: 'FogCachedShadowAtlasHeight', value: '0' },
    { path: ['SceneSystem'], key: 'FogCachedShadowAtlasWidth', value: '0' },
    { path: ['SceneSystem'], key: 'FogCachedShadowTileSize', value: '0' },
    { path: ['SceneSystem'], key: 'GpuLightBinnerBinEnvMaps', value: '1' },
    { path: ['SceneSystem'], key: 'GpuLightBinnerBinLPVs', value: '1' },
    { path: ['SceneSystem'], key: 'GpuLightBinnerSupportViewModelCascade', value: '0' },
    { path: ['SceneSystem'], key: 'HairShading', value: 'false' },
    { path: ['SceneSystem'], key: 'HDRFrameBuffer', value: '0' },
    { path: ['SceneSystem'], key: 'LayerBatchThresholdFullsort', value: '80' },
    { path: ['SceneSystem'], key: 'LightCookieAllocGranularity', value: '1' },
    { path: ['SceneSystem'], key: 'LightCookieMinAllocSize', value: '0' },
    { path: ['SceneSystem'], key: 'NonTexturedGradientFog', value: '0' },
    { path: ['SceneSystem'], key: 'ParticleBufferSize', value: '256' },
    { path: ['SceneSystem'], key: 'PointLightShadowsEnabled', value: '1' },
    { path: ['SceneSystem'], key: 'SparseShadowTrees', value: '1' },
    { path: ['SceneSystem'], key: 'SunLightMaxCascadeSize', value: '2' },
    { path: ['SceneSystem'], key: 'SupportsInstancedFade', value: '0' },
    { path: ['SceneSystem'], key: 'VolumetricFog', value: '0' },
    { path: ['SceneSystem'], key: 'CSMCascadeResolution', remove: true },
    { path: ['SceneSystem'], key: 'CubemapFog', remove: true },
    { path: ['SceneSystem'], key: 'DefaultShadowTextureHeight', remove: true },
    { path: ['SceneSystem'], key: 'DefaultShadowTextureWidth', remove: true },
    { path: ['WorldRenderer'], key: 'EnvironmentMapCacheSize', value: '256' },
    { path: ['WorldRenderer'], key: 'GrassCastsShadows', value: '0' },
    { path: ['WorldRenderer'], key: 'LPVEdgeBlending', value: '0' },
];

/** Convar -> value, in the order the active keys appear in the upstream
 *  config. Keys already present in the user's ConVars block are edited in
 *  place; the rest are injected as a marked block at the top of ConVars
 *  (upstream's own documented insertion point). */
export const CONVARS: ReadonlyArray<readonly [string, string]> = [
    ['r_particle_max_size_cull', '700'],
    ['steam_inputhandler_enabled', 'true'],
    ['citadel_unit_status_allies_see_thru_walls', 'true'],
    ['citadel_boss_glow_disabled', '1'],
    ['citadel_damage_offscreen_indicator_disabled', 'true'],
    ['citadel_player_glow_disabled', '0'],
    ['citadel_trooper_glow_disabled', '1'],
    ['citadel_unit_status_allies_see_thru_walls_max_distance', '40'],
    ['citadel_unit_status_delta_decay_rate', '2'],
    ['citadel_crosshair_hit_marker_duration', '0.00001'],
    ['citadel_damage_report_enable', '1'],
    ['citadel_damage_text_batching_window_ability', '1000'],
    ['citadel_hideout_ball_show_juggle_count', '1'],
    ['citadel_hideout_ball_show_juggle_fx', '1'],
    ['citadel_hud_objective_health_enabled', '2'],
    ['citadel_unit_status_use_new', 'true'],
    ['citadel_show_chat_wheel_angle_threshold', '0'],
    ['lb_enable_baked_shadows', '0'],
    ['lb_enable_dynamic_lights', '1'],
    ['lb_enable_stationary_lights', '0'],
    ['r_draw3dskybox', '0'],
    ['engine_low_latency_sleep_after_client_tick', 'true'],
    ['engine_no_focus_sleep', '20'],
    ['fps_max', '0'],
    ['panorama_max_fps', '30'],
    ['panorama_max_overlay_fps', '30'],
    ['r_size_cull_threshold', '0.9'],
    ['citadel_camera_use_vmdl_flatten_horizontal', 'false'],
    ['citadel_camera_use_vmdl_flatten_vertical', 'false'],
    ['citadel_camera_soft_collision_angle', '360'],
    ['r_citadel_clip_sphere_min_opacity', '0'],
    ['r_texture_budget_threshold', '0.7'],
    ['r_texture_budget_update_period', '0.5'],
    ['r_texture_stream_mip_bias', '3'],
    ['r_texturefilteringquality', '3'],
    ['r_farz', '7000'],
    ['r_mapextents', '7000'],
    ['thread_pool_option', '-1'],
    ['citadel_damage_text_show_effectiveness', '0'],
    ['closecaption', 'false'],
    ['panorama_allow_transitions', 'false'],
    ['panorama_disable_blur', '1'],
    ['panorama_disable_box_shadow', '1'],
    ['panorama_temp_comp_layer_min_dimension', '128'],
    ['r_citadel_enable_pano_world_blur', 'true'],
    ['r_dashboard_render_quality', '0'],
    ['r_citadel_shadow_caching', 'false'],
    ['cl_globallight_shadow_mode', '0'],
    ['lb_barnlight_shadowmap_scale', '0.5'],
    ['lb_csm_cascade_size_override', '1'],
    ['lb_csm_draw_alpha_tested', '0'],
    ['lb_csm_draw_translucent', '0'],
    ['lb_csm_override_staticgeo_cascades', '0'],
    ['lb_csm_override_staticgeo_cascades_value', '-1'],
    ['lb_dynamic_shadow_resolution_base', '256'],
    ['lb_enable_shadow_casting', '0'],
    ['lb_ssss_samples', '1'],
    ['lb_sun_csm_size_cull_threshold_texels', '30'],
    ['r_citadel_gpu_culling_shadows', '1'],
    ['r_citadel_shadow_quality', '0'],
    ['r_shadows', '0'],
    ['r_size_cull_threshold_shadow', '1'],
    ['sc_disable_spotlight_shadows', '1'],
    ['sparseshadowtree_disable_for_viewmodel', '0'],
    ['sparseshadowtree_enable_rendering', '1'],
    ['mat_max_lighting_complexity', '1'],
    ['cl_retire_low_priority_lights', '1'],
    ['mat_async_shader_load', '1'],
    ['mat_set_shader_quality', '0'],
    ['r_citadel_distancefield_farfield_enable', '0'],
    ['r_citadel_ssao_quality', '0'],
    ['r_citadel_ssao_thin_occluder_compensation', '0'],
    ['r_citadel_sun_shadow_slope_scale_depth_bias', '1.0'],
    ['r_directlighting', 'false'],
    ['r_distancefield_enable', '0'],
    ['r_light_flickering_enabled', '1'],
    ['r_lightmap_bicubic_filtering', '1'],
    ['r_lightmap_size', '4'],
    ['r_lightmap_size_directional_irradiance', '4'],
    ['r_multiscattering', '1'],
    ['r_rendersun', '0'],
    ['r_ssao', '0'],
    ['r_ssao_strength', '0'],
    ['cl_disable_ragdolls', '0'],
    ['cl_ragdoll_limit', '-1'],
    ['ragdoll_parallel_pose_control', '1'],
    ['animgraph_enable_parallel_op_evaluation', '1'],
    ['animgraph_enable_parallel_preupdate', '1'],
    ['cl_fasttempentcollision', '1000'],
    ['cloth_sim_on_tick', '0'],
    ['enable_boneflex', '0'],
    ['ik_fabrik_align_chain', '0'],
    ['ik_final_fixup_enable', '0'],
    ['phys_threaded_cloth_bone_update', '1'],
    ['phys_threaded_kinematic_bone_update', '1'],
    ['phys_threaded_transform_update', '1'],
    ['props_break_max_pieces_perframe', '0'],
    ['r_hair_ao', '0'],
    ['cl_show_splashes', '0'],
    ['mat_colorcorrection', '1'],
    ['r_character_decal_resolution', '1'],
    ['r_decals', '1'],
    ['r_decals_default_fade_duration', '1'],
    ['r_depth_of_field', '0'],
    ['r_drawdecals', '1'],
    ['r_effects_bloom', '0'],
    ['r_post_bloom', '0'],
    ['sc_clutter_enable', 'false'],
    ['violence_ablood', '0'],
    ['violence_agibs', '0'],
    ['violence_hblood', '0'],
    ['violence_hgibs', '0'],
    ['volume_fog_intermediate_textures_hdr', 'false'],
    ['cl_async_usercmd_send', 'true'],
    ['cl_input_enable_raw_keyboard', '1'],
    ['particle_cluster_use_collision_hulls', 'false'],
    ['r_update_particles_on_render_only_frames', 'true'],
    ['r_particle_fixedrandomseeds', 'true'],
    ['r_citadel_screenspace_particles_full_res', 'true'],
    ['r_particle_mixed_resolution_viewstart', '16'],
    ['cl_particle_batch_mode', '1'],
    ['cl_particle_fallback_base', '10'],
    ['cl_particle_fallback_multiplier', '20'],
    ['cl_particle_sim_fallback_base_multiplier', '40'],
    ['cl_particle_sim_fallback_threshold_ms', '1'],
    ['particle_cluster_nodraw', '1'],
    ['r_RainParticleDensity', '0'],
    ['r_draw_particle_children_with_parents', '0'],
    ['r_late_particle_job_sync', 'true'],
    ['r_limit_particle_job_duration', 'true'],
    ['r_particle_allowprerender', 'false'],
    ['r_particle_batch_collections', 'true'],
    ['r_particle_max_detail_level', '1'],
    ['r_particle_max_texture_layers', '4'],
    ['r_particle_model_per_thread_count', '64'],
    ['r_particle_skip_postsim', 'true'],
    ['r_physics_particle_op_spawn_scale', '0'],
    ['r_world_wind_strength', '0'],
    ['sc_allow_dithered_lod', 'false'],
    ['citadel_use_pvs_for_players', 'true'],
    ['mat_viewportscale', '0.01'],
    ['phys_cull_internal_mesh_contacts', 'true'],
    ['sc_aggregate_bvh_threshold', '128'],
    ['sc_fade_distance_scale_override', '100'],
    ['sc_instanced_mesh_lod_bias', '0.15'],
    ['sc_instanced_mesh_lod_bias_shadow', '0.10'],
    ['sc_instanced_mesh_motion_vectors', '0'],
    ['sc_instanced_mesh_size_cull_bias_shadow', '10'],
    ['sc_layer_batch_threshold', '128'],
    ['sc_layer_batch_threshold_fullsort', '80'],
    ['sc_screen_size_lod_scale_override', '0.5'],
    ['skeleton_instance_lod_optimization', 'false'],
    ['r_citadel_gpu_culling', 'true'],
    ['r_force_zprepass', '0'],
    ['r_vma_defrag_algorithm', '0'],
    ['rtx_dynamic_blas', 'false'],
    ['rtx_dynamic_blas_caching', 'false'],
    ['rtx_force_default_hitgroup', 'true'],
    ['rtx_texture_resolution', '64'],
    ['citadel_video_preset', '2'],
    ['sc_instanced_mesh_opaque_fade', 'false'],
    ['cl_frametime_summary_report_detailed', 'false'],
    ['citadel_perf_interval_report_s', '100000'],
    ['disable_source_soundscape_trace', 'true'],
    ['cc_captiontrace', '0'],
    ['r_particle_model_new', 'false'],
    ['r_particle_model_new8', 'false'],
    ['r_pixelvisibility_partial', 'false'],
    ['r_skip_precache_validation_check', 'true'],
    ['cl_batch_entity_list_ops_during_latch', 'true'],
    ['cl_interp_parallel', 'true'],
    ['cl_modifier_parallel_gather_status_effect_updates', 'true'],
    ['cl_phys_assume_fixed_tick_interval', 'false'],
    ['engine_max_ticks_to_simulate', '2'],
    ['nav_obstruction_async_update', 'true'],
    ['parallel_perform_invalidate_physics', 'true'],
    ['r_async_compute_fog', 'true'],
    ['r_citadel_depth_prepass_dynamic_objects', 'false'],
    ['r_low_latency', '1'],
    ['r_renderdoc_auto_shader_pdbs', 'false'],
    ['save_parallel', 'true'],
    ['sc_force_materials_batchable', 'true'],
    ['r_max_portal_render_targets', '2'],
    ['r_grass_end_fade', '0'],
    ['r_grass_quality', '0'],
    ['r_grass_start_fade', '0'],
    ['ai_strong_optimizations_no_checkstand', '1'],
    ['citadel_npc_force_animate_every_tick', 'false'],
    ['cl_simulate_dormant_entities', 'false'],
    ['audio_enable_vmix_mastering', 'false'],
    ['snd_mixahead', '0.05'],
    ['snd_occlusion_bounces', '0'],
    ['snd_occlusion_rays', '0'],
    ['snd_soundmixer_version', '1'],
    ['snd_steamaudio_reverb_order_rendering', '0'],
    ['snd_ui_positional', 'false'],
    ['snd_steamaudio_num_threads', '4'],
    ['csm_cascade0_override_dist', '0'],
    ['csm_cascade1_override_dist', '0'],
    ['csm_cascade2_override_dist', '0'],
    ['csm_cascade3_override_dist', '0'],
    ['csm_max_dist_between_caster_and_receiver', '0'],
    ['csm_max_num_cascades_override', '0'],
    ['csm_max_shadow_dist_override', '1'],
    ['csm_max_visible_dist', '0'],
    ['csm_res_override_0', '1'],
    ['csm_res_override_1', '1'],
    ['csm_res_override_2', '1'],
    ['csm_res_override_3', '1'],
    ['csm_viewmodel_shadows', 'false'],
    ['cl_joystick_enabled', '1'],
    ['panorama_joystick_enabled', '1'],

];
